### ISSUE TITLE
Ingen problemer her, hilsen mig

### ISSUE THREAD

**Issue by benja1904** [TheMetalix404/mafz#2]
\documentclass[12pt]{article}
\usepackage{microtype}
\microtypesetup{
    protrusion = true,
    expansion = true,
    tracking = true,
    activate = {true, nocompatibility}
}
\usepackage[utf8]{inputenc}
\usepackage[T1]{fontenc}
\usepackage{mathtools, amssymb}
\usepackage{geometry}
\usepackage{graphicx}
\usepackage{fancyhdr}
\usepackage{tcolorbox}
\usepackage{xcolor}
\usepackage{enumitem}
\usepackage{pgfplots}
\pgfplotsset{compat = 1.18}
\usepackage{pgfplotstable}
\usepackage{hyperref}
\hypersetup{
    colorlinks = true,
    linkcolor = blue,
    filecolor = magenta,      
    urlcolor = blue,
    pdftitle = {Funktioner},
    pdfsubject = {Matematik},
    pdfauthor = {Benjamin Vind Nisted, Klo og Pico},
    pdfkeywords = {Matematik, funktioner, monotoniforhold, toppunkt, differentialregning},
}

\usepackage{tikz}
\usetikzlibrary{tikzmark}
\usepackage{cancel}
\usepackage{witharrows}
\usepackage{esvect}
\usepackage{multicol}
\usepackage{float}
\usepackage[skip = 12pt]{parskip}
\usepackage{lastpage}
\usepackage{makecell}
\usepackage{nameref}

\definecolor{darkblue}{HTML}{6f9cde}
\definecolor{lightergray}{gray}{0.95}
\frenchspacing
\geometry{a4paper, margin = 1in, headsep = 1.3cm}
\pagestyle{fancy}
\fancyhf{}
\rhead{\today \\ Matematik}
\lhead{22xvx \\ Benjamin, Ruben og Frida}
\setlist[itemize]{parsep = 8pt}
\setlist[enumerate]{parsep = 8pt}
\graphicspath{{Billeder}}

\pagestyle{fancy}
\addtolength{\headheight}{\baselineskip}
\setlength{\headheight}{27.12pt}
\fancyfoot[R]{Side \thepage\ af \pageref{LastPage}}
\setcounter{secnumdepth}{0}
\renewcommand{\headrulewidth}{0.1pt}
\renewcommand{\footrulewidth}{0pt}
\renewcommand{\contentsname}{Indholdsfortegnelse}
\renewcommand{\figurename}{Figur}
\renewcommand{\arraystretch}{1.6}
\renewcommand{\today}{\number\day.\space%
\ifcase\month\or januar\or februar\or marts\or april\or maj\or juni\or juli\or august\or september\or oktober\or november\or december\fi%
\space\number\year}

\begin{document}

\begin{titlepage}
    \centering
    \vspace*{\fill}
    {\Huge Matematikaflevering}
    \vskip .2cm
    {\Large\itshape Uge 39\par}
    \vskip 2cm
    \includegraphics[width = 0.6\textwidth]{logo.png}
    \vskip 2cm
    {\large Benjamin, Ruben og Frida\par}
    {\large 22xvx\par}
    \vfill
    {\large \today\par}
    \vspace*{\fill}
\end{titlepage}

\newpage

\thispagestyle{empty}
\pagenumbering{gobble}
\tableofcontents

\newpage

\pagenumbering{arabic}
\section{Opgave 1}

\subsection{a)}

Da funktionen følger forskriften $f(t) = a\cdot sin\cdot (\omega\cdot t + \phi) + k$, er $\omega = 3$. Derfor kan man beregne svingningstiden $T$:

\[
    T = \frac{2\pi}{\omega} 
\]

\[
    T = \frac{2\pi}{3} = \colorbox{yellow}{$2,09$}
\]

\subsection{b)}
$f(t)$ svarer til $f(x)$. Når $x = 0$, må y-koordinatet ligge på y-aksen. Derfor kan man indsætte 0 på t's plads for at få grafens skæring med y-aksen:
\[
    2\cdot \sin(3\cdot 0 + 0,5) + 1 = \colorbox{yellow}{1,96}
\]

\subsection{c)}
solve(f(x), x) = 0.0)

0,36?

\section{Opgave 2}
    
\subsection{a)}
Tangentens ligning

\subsection{b)}
Vi har forskriften $f(x) = -x^2 -3x + 4$ og punkterne $A(-8, 6)$ og $B(4, 10)$   

For at finde ligningerne for den parallelle parabeltangenten, kan vi se på hældningen
\[
    a = \frac{\Delta y}{\Delta x}
\]

Hældningen på linjen gennem punkt $A$ og $B$ er:
\[
    a = \frac{10 - 6}{4 - (-8)} = \frac{4}{12} = \frac{1}{3}
\]

Nu finder vi den afledte funktion og sætter den lig med hældningen for linjen genne punkterne, da de så vil være parallelle:
\[
    f'(x) = \frac{1}{3} = -\frac{5}{3}
\]

Nu kan vi sætte denne x-værdi ind i tangentens ligning, og isolere for y:
\[
    y = f\left(-\frac{5}{3}\right) + f'\left(-\frac{5}{3}\right) \cdot \left(x - \left(-\frac{5}{3}\right)\right) = \frac{61}{9} + \frac{x}{3} 
\]

Ny har vi x og y, og forskriften vil derfor være:
\[
    \colorbox{yellow}{$y_3 = \frac{1}{3}x + \frac{61}{9}$}
\]

Eller
\[
    y_3 = \frac{x}{3} + \frac{61}{9}
\]

\section{Opgave 3}

\subsection{a)}

Vi har forskriften:
\[
    f'(x) = -x^2 - 
\]

For at 

\subsection{b)}
solve(f(x), x) = 0.0)

\subsection{c)}

f(x) = :)

f(x) = :|

Du besvarer blot opgaven Ruben, og det er nu!

\end{document}

**Comment by TheMetalix404** [comment]
tusinde tak for den fantastiske ændring og for at lave min opgave. vil du ikke næste gang være sød at lave en pull request i stedet for en issue, da det giver bedre mening. så anvender du featuresne som det var meningen. tak på forhånd

KI kan generere falske informationer
