### ISSUE TITLE
nyt problem hurtigt

### ISSUE THREAD

**Issue by benja1904** [TheMetalix404/mafz#4]
\documentclass[12pt]{article}

\begin{document}

\section{Opgave 1}

\subsection{a)}

Da funktionen følger forskriften $f(t) = a\cdot sin\cdot (\omega\cdot t + \phi) + k$, er $\omega = 3$. Derfor kan man beregne svingningstiden $T$:

$$
    T = \frac{2\pi}{\omega} 
$$

$$
    T = \frac{2\pi}{3} = \colorbox{yellow}{$2,09$}
$$

\subsection{b)}
$f(t)$ svarer til $f(x)$. Når $x = 0$, må y-koordinatet ligge på y-aksen. Derfor kan man indsætte 0 på t's plads for at få grafens skæring med y-aksen:
$$
    2\cdot \sin(3\cdot 0 + 0,5) + 1 = \colorbox{yellow}{1,96}
$$

\subsection{c)}
solve(f(x), x) = 0.0)

0,36?

\section{Opgave 2}
    
\subsection{a)}
Tangentens ligning

\subsection{b)}
Vi har forskriften $f(x) = -x^2 -3x + 4$ og punkterne $A(-8, 6)$ og $B(4, 10)$   

For at finde ligningerne for den parallelle parabeltangenten, kan vi se på hældningen
$$
    a = \frac{\Delta y}{\Delta x}
$$

Hældningen på linjen gennem punkt $A$ og $B$ er:
$$
    a = \frac{10 - 6}{4 - (-8)} = \frac{4}{12} = \frac{1}{3}
$$

Nu finder vi den afledte funktion og sætter den lig med hældningen for linjen genne punkterne, da de så vil være parallelle:
$$
    f'(x) = \frac{1}{3} = -\frac{5}{3}
$$

Nu kan vi sætte denne x-værdi ind i tangentens ligning, og isolere for y:
$$
    y = f\left(-\frac{5}{3}\right) + f'\left(-\frac{5}{3}\right) \cdot \left(x - \left(-\frac{5}{3}\right)\right) = \frac{61}{9} + \frac{x}{3} 
$$

Ny har vi x og y, og forskriften vil derfor være:
$$
    \colorbox{yellow}{$y_3 = \frac{1}{3}x + \frac{61}{9}$}
$$

Eller
$$
    y_3 = \frac{x}{3} + \frac{61}{9}
$$

\section{Opgave 3}

\subsection{a)}

Vi har forskriften:
$$
    f'(x) = -x^2 - 
$$

For at 

\subsection{b)}
solve(f(x), x) = 0.0)

\subsection{c)}

f(x) = :)

f(x) = :|

Du besvarer blot opgaven Ruben, og det er nu!

\end{document}

**Comment by TheMetalix404** [comment]
f'(x)
